version: '3'

services:
  db:
    container_name: "db"
    image: postgres:16
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
#    volumes:
#      - dev-db:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
    platform: linux/amd64


#volumes:
#  dev-db: